train_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./datasets/IXI-T2-MidSlices/train x4
      root_path_2: ./datasets/IXI-T2-MidSlices/train
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-implicit-paired
    args:
      inp_size: 64
      augment: true
  batch_size: 16

val_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./datasets/IXI-T2-MidSlices/val x4
      root_path_2: ./datasets/IXI-T2-MidSlices/val
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-paired
    args:
      inp_size: 64
  batch_size: 16

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: liif
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        scale: 4
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256, 256, 256, 256]

optimizer:
  name: adam
  args:
    lr: 1.e-6
epoch_max: 1000
multi_step_lr:
  milestones: [60, 80, 100, 120]
  gamma: 0.5

epoch_val: 1
epoch_save: 10

resume: ./save/train_HIGH_MAED_LIIF-x4_IXI/epoch-last.pth