train_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./datasets/IXI-T2-MidSlices/train x4
      root_path_2: ./datasets/IXI-T2-MidSlices/train x2
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-implicit-paired
    args:
      inp_size: 64
      augment: true
  batch_size: 16
val_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./datasets/IXI-T2-MidSlices/val x4
      root_path_2: ./datasets/IXI-T2-MidSlices/val x2
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-paired
    args:
      inp_size: 64
  batch_size: 16
data_norm:
  inp:
    sub:
    - 0.5
    div:
    - 0.5
  gt:
    sub:
    - 0.5
    div:
    - 0.5
model:
  name: liif
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        scale: 2
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list:
        - 128
        - 128
        - 128
        - 128
optimizer:
  name: adam
  args:
    lr: 5.0e-05
epoch_max: 1000
multi_step_lr:
  milestones:
  - 40
  - 80
  - 120
  - 160
  gamma: 0.5
epoch_val: 1
epoch_save: 10
resume: ./save/train_MAED_LIIF-x2_OOD_IXI/epoch-last.pth
