test_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./datasets/IXI-T2-MidSlices/test x4
      root_path_2: ./datasets/IXI-T2-MidSlices/test 
  wrapper:
    name: sr-implicit-paired
    args: {}
  batch_size: 1
eval_bsize: 30000

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}